# Generated by Django 4.2.11 on 2026-03-04 22:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_vcpus', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Макс. vCPU')),
                ('used_vcpus', models.PositiveIntegerField(default=0, verbose_name='Использовано vCPU')),
                ('max_ram_mb', models.PositiveIntegerField(default=20480, validators=[django.core.validators.MinValueValidator(512)], verbose_name='Макс. RAM (MB)')),
                ('used_ram_mb', models.PositiveIntegerField(default=0, verbose_name='Использовано RAM (MB)')),
                ('max_disk_gb', models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Макс. диск (GB)')),
                ('used_disk_gb', models.PositiveIntegerField(default=0, verbose_name='Использовано диска (GB)')),
                ('max_vms', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Макс. VM')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='accounts.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Квота ресурсов',
                'verbose_name_plural': 'Квоты ресурсов',
                'db_table': 'resource_quotas',
            },
        ),
    ]
