# Generated by Django 4.2.11 on 2026-03-04 22:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hypervisors', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя VM')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('vcpus', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='vCPU')),
                ('ram_mb', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(512)], verbose_name='RAM (MB)')),
                ('disk_gb', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Диск (GB)')),
                ('os_type', models.CharField(choices=[('ubuntu-22.04', 'Ubuntu 22.04 LTS'), ('ubuntu-20.04', 'Ubuntu 20.04 LTS'), ('debian-12', 'Debian 12'), ('centos-9', 'CentOS Stream 9'), ('rocky-9', 'Rocky Linux 9'), ('windows-2022', 'Windows Server 2022')], max_length=50, verbose_name='ОС')),
                ('libvirt_uuid', models.UUIDField(blank=True, null=True, verbose_name='UUID в libvirt')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('running', 'Running'), ('stopped', 'Stopped'), ('paused', 'Paused'), ('restarting', 'Restarting'), ('error', 'Error'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vms', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('hypervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_machines', to='hypervisors.hypervisor', verbose_name='Гипервизор')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='accounts.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Виртуальная машина',
                'verbose_name_plural': 'Виртуальные машины',
                'db_table': 'virtual_machines',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='virtual_mac_organiz_213339_idx'), models.Index(fields=['hypervisor', 'status'], name='virtual_mac_hypervi_579e1d_idx')],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
