# Generated by Django 4.2.11 on 2026-03-05 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('virtual_machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_machines', to='accounts.organization', verbose_name='Организация'),
        ),
    ]
