# Generated by Django 4.2.11 on 2026-03-04 22:44

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя')),
                ('host', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('port', models.PositiveIntegerField(default=16509, verbose_name='Порт libvirt')),
                ('total_vcpus', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_ram_mb', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(512)])),
                ('total_disk_gb', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('used_vcpus', models.PositiveIntegerField(default=0)),
                ('used_ram_mb', models.PositiveIntegerField(default=0)),
                ('used_disk_gb', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='online', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Гипервизор',
                'verbose_name_plural': 'Гипервизоры',
                'db_table': 'hypervisors',
                'ordering': ['name'],
            },
        ),
    ]
